- README.md
> add Bountysource badge to readme

- .travis.yml
- CMakeLists.txt
- README.md
> add desktop validate test

- .travis.yml
- CMakeLists.txt
Fixes #11 
- Added `appstreamcli validate` to ctests
- Added `appstream` to travis dependencies
> Add appstream test

- src/MainWindow.vala
- Remove unused constants
- Organize variables
- GObject-style construction
- Remove whitespace
> clean up mainwindow.vala

- data/CMakeLists.txt
Fixes #26 
- Change directory to metainfo
> Update appstream data install directory

- src/MainWindow.vala
- src/Widgets/HeaderBar.vala
Fixes #49
While we're here, get rid of this connect signals method and clean up this recording property stuff
> Add timer while recording video

- meson.build
- src/Widgets/HeaderBar.vala
- src/Widgets/ModeSwitch.vala
Supersedes #53 and #48 
Fixes #47 
This uses the mode switch widget I wrote for LookBook
> Use mode switch to change photo/video

- README.md
- data/io.elementary.camera.appdata.xml.in
> Add screenshot and OARS

- src/MainWindow.vala
> Make connecting label translatable

- src/MainWindow.vala
- src/Widgets/HeaderBar.vala
Ports just the GLib.Action code from #93, but with bug fixes and DRYing
> Use GLib.Action for taking photo and video

- .github/workflows/main.yml
- README.md
- meson.build
- src/MainWindow.vala
- src/Widgets/HeaderBar.vala
Do the least to get rounded window
> MainWindow: Subclass Hdy.Window

- README.md
- src/MainWindow.vala
> Prevent multiple timers running at the same time

- data/meson.build
- meson_options.txt
add a meson option to skip the tests since it's adding a unnecessary dependency on appstreamcli for flatpak.
> add option to skip tests

- data/icons/128/accessories-camera.svg
- data/icons/16/accessories-camera.svg
- data/icons/24/accessories-camera.svg
- data/icons/32/accessories-camera.svg
- data/icons/48/accessories-camera.svg
- data/icons/64/accessories-camera.svg
- data/meson.build
So we don't need to manually install them from the icons repository in the manifest.
> Install icons with the build

- .github/workflows/main.yml
- io.elementary.camera.yml
> Add flatpak

- src/MainWindow.vala
- src/Widgets/CameraView.vala
- src/Widgets/HeaderBar.vala
Make use of properties on the go.
Fixes #147
> HeaderBar: Fix horizontal flip being out of sync with the flip state.

- io.elementary.camera.yml
> Flatpak manifest: use daily platform

- src/MainWindow.vala
- src/Widgets/CameraView.vala
- src/Widgets/HeaderBar.vala
This fixes #155 and #72 . When no camera is present this PR shows the adequate view and disables all controls. When a camera is plugged it enables all controls and shows it.
> When no camera is present show view and disable all controls.

- .github/workflows/ci.yml
- .github/workflows/merge.yml
Like https://github.com/elementary/calculator/pull/180
> Actions: use elementary container

- .github/workflows/ci.yml
- .github/workflows/merge.yml
We need it to have the "daily" branch to work properly
> ci: Use flatpak-builder@master until @v4 is available

- src/Widgets/CameraView.vala
Could be there is a reason why it is that way, but everything else (shouldn't be) isn't.
> Spelling: Could not

- .github/workflows/release.yml
- data/io.elementary.camera.appdata.xml.in
- io.elementary.camera.yml
- meson.build
> Release 6.0.0

- io.elementary.camera.yml
No longer needed because of new settings portal
> Flatpak: Remove accountsservice hole

- README.md
Noticed when debugging an issue today
> README: correct deps

- src/Widgets/CameraView.vala
- src/Widgets/HeaderBar.vala
In preparation for GTK4 changes.
@danrabbit I hope this is correct. Thanks
> Replace Grids with Box for GTK4 preparation

- src/Widgets/CameraView.vala
Allow to decode the raw source from the camera.
> CameraView: Add decodebin

- data/camera.metainfo.xml.in
- meson.build
> Release 8.0.0

- src/Widgets/CameraView.vala
> Always use decimal point
