elementary/camera

.travis.yml
Fixes #14
- Use official elementary OS docker containers for testing Loki stable and unstable
=> Use official elementary OS docker containers

src/MainWindow.vala, src/Widgets/HeaderBar.vala
- Change `void set_camera_controls_sensitive ()` to a `bool camera_controls_sensitive`
- Organize to not mix up private and public variables
- Use `construct`
- `width request` instead of `set_size_request`
- Remove unused style class RAISED
- Remove extra whitespace
=> headerbar cleanup

.travis.yml, CMakeLists.txt, README.md, src/Utils.vala, src/Widgets/CameraView.vala
Adds a shutter sound when taking a photo. From issue #7 
- Uses GSound to play the stock "camera-shutter" sound when a photo is being taken
- Depends on libgsound-dev (added in readme)
- Tested on Fedora 25 (Gnome), haven't tested on elementary OS
- I can't work out how to do the flash yet
=> Add shutter sound

src/Application.vala, src/Backend/Settings.vala, src/MainWindow.vala, src/Utils.vala, src/Widgets/CameraView.vala, src/Widgets/HeaderBar.vala, src/Widgets/LoadingView.vala
Fixes https://bugs.launchpad.net/snap-elementary/+bug/1653413
- Updates Free Software Foundation address in license headers
=> Update fsf address

src/MainWindow.vala
This sets the resolution to 640×480, which appears to be the default for Cheese as well (which is why Cheese often works with certain higher-res cameras when Camera does not). Ideally we could be smarter about this and _possibly_ even expose supported resolutions, but this at least gets it working as well as Cheese ootb.
I've kept this as a draft because I doubt we'd be okay just dropping to this resolution full-time, so it'll need some input and thought.
=> Cap Resolution

src/MainWindow.vala
Fixes #103
- removing ` && camera_devices[0].get_name () != null`
My webcam name is "null", that's why the app wasn't working. After removing this part of code everything works fine.
=> Handle null camera name

src/Widgets/HeaderBar.vala, src/Widgets/TimerButton.vala
Use the `always_show_image` property instead of manually packing a grid
For some reason Gtk complains if we add the image inside the button subclass, so we do it in headerbar
=> TimerButton: simpler image and label

data/icons/symbolic/object-inverse-symbolic.svg, data/io.elementary.camera.gresource.xml, src/MainWindow.vala, src/Widgets/CameraView.vala, src/Widgets/HeaderBar.vala
Fix #51  : adds app menu for adjusting brightness and contrast. Most of the design is based on the prototype in #67 . I added the contrast option below, using the `night-light-symbolic` icon. 
Following the discussions in #67 , IMHO this feature should be in camera as it is useful for recording videos. Although photo editing works well in the *Photos* app, doing this kind of adjustment for videos is much harder and time consuming. Also, all the heavy lifting is done using plugins in GStreamer so there's no need to maintain the same set of filters implemented in two different places. 
Currently these settings are not persistent.
=> Add brightness and contrast adjustments

src/MainWindow.vala
We started shipping RDNN icons in Camera a while ago
=> MainWindow: Use RDNN icon name

src/Widgets/CameraView.vala
Fix #148 : no audio recording gstreamer elements were being created. This PR creates them when the record button is pressed. The default audio source is used with its default properties.
=> Add audio recording elements to record_bin.

data/io.elementary.camera.appdata.xml.in
This is needed for appstream-generator to find the associated desktop file.
See also:
- https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-launchable
- https://github.com/ximion/appstream-generator/issues/88
=> Add launchable tag to appdata

src/MainWindow.vala
* Do not use deprecated code
Following premature merge of 64b24d9f1019d3a8c536d75605d951c80a4b23d6 :disappointed:
=> Construct launch context properly

.gitignore, src/MainWindow.vala, src/Widgets/CameraView.vala, src/Widgets/HeaderBar.vala
Fixes #182 
Fixes #186 
This PR is intended to fix some problems related to having two cameras installed (see https://github.com/elementary/camera/issues/182#issuecomment-953182535 for something this might fix).  If the cameras have the same name or if `start_view` is re-entered before the pipeline is setup then no picture is shown.  Some code clean up and simplification was also done, saving some code and reducing the number of entities.
* Pass Device objects between functions and in signals
* Lose unneeded list of devices - store in menuitems
* Lose unneeded camera_present signal
* Headerbar takes care of enabling controls
* Simplify
=> Do not rely on display name to distinguish devices

src/Widgets/HeaderBar.vala
The camera_menu_button is duplicated in HeaderBar.vala so it must be removed.
=> Fix Duplicated MenuButton declaration

src/Widgets/CameraView.vala
=> Fix jpeg pipeline

src/Widgets/CameraView.vala
Using the included element is more reliable than recreating it by hand. Allows
to use a different source than v4l2.
=> CameraView: Create the camera source using the GStreamer element

src/Widgets/CameraView.vala
Otherwise fallback to the non-GL view.
=> CameraView: Use GtkGLSink when possible

src/Widgets/CameraView.vala
This ensures that we don't use all the resources just to show a preview.
=> CameraView: limit the max rate to 30fps in the preview

src/Widgets/CameraView.vala
Fixes #221
Incidentally fixes #7 (?)
This recreates the current pipeline after take photo instead of setting the state to PLAYING (which does not seem to work after setting the state to NULL).
This incidentally provides a possible fix for #7 since the preview goes black while the pipeline is recreated.  The sound effect is played just before recreating the pipeline so the sound and visual effects are more closely synchronized.
I suspect more elegant solutions are possible but I am not sufficiently knowledgeable of GStreamer atm.
=> Ensure pipeline restarts and controls function after taking photo

src/Widgets/CameraView.vala
This aims to prepare `CameraView.vala` for `GTK4` since we can't subclass `Gtk.Stack` in `GTK4` anymore. I tried using `Gtk.Widget` (Gtk3 version), but it seems that it cannot have children on its own without using `Gtk.Container` unlike the `Gtk.Widget` in GTK4. However, using `Gtk.Container` for now will not cause significant regressions when we use `Gtk.Widget` for GTK4.
@jeremypw @danrabbit this is the new pr because I might had accidentally deleted my fork.
=> Prepare CameraView for GTK4

data/io.elementary.camera.appdata.xml.in, src/Widgets/CameraView.vala
Here we are making sure to display an error message to the user in case there is no camera device available at all. Before this change the Camera app does start showing an endlessly spinning spinner which leaves the user under the impression of the app not working correctly.
Tested this in a VM, which shows the error message after 2s - and on bare metal where the camera is still initialized correctly.
=> Show error in case no camera device is available

src/Widgets/CameraView.vala
Turned out there is another capability needed to support some webcams which produce MJPEG streams. They don't advertise the `video/x-raw` capability but support `image/jpeg` instead: https://oz9aec.net/software/gstreamer/webcam-pixel-formats-and-gstreamer-caps-filters
This PR makes sure we are filtering for any one of those two capabilities when looking for a supported device. This fixes #236 (see screenshot below) and _might_ fix as well (needs testing from the corresponding users): https://github.com/elementary/camera/issues/175, https://github.com/elementary/camera/issues/151, https://github.com/elementary/camera/issues/149, https://github.com/elementary/camera/issues/121, https://github.com/elementary/camera/issues/115
=> Add image/jpeg caps to device filter to support MJPEG webcams

data/meson.build, po/extra/meson.build, po/meson.build
Fixes the following warning on build:
```
WARNING: Deprecated features used:
* 0.56.0: {'meson.source_root'}
```
=> meson: Fix deprecated source_root

README.md
=> Readme: use flatpak builder

src/MainWindow.vala
Fixes #275
Testes on a PC with no cameras and on a MacBook Air with an iSight camera.
=> MainWindow: Make headerbar buttons insensitive by default

io.elementary.camera.yml
Fixes the following warning when building with flatpak-builder:
```
warning: redirecting to https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs.git/
Fetching git repo https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs, ref refs/heads/0.12
warning: redirecting to https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs.git/
```
=> Flatpak: Fix warning about redirect
